# Generated by Django 4.0.5 on 2023-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('height', models.IntegerField(default=0, null=True)),
                ('govID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dob', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('lastLoc', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('policeStation', models.CharField(max_length=255, null=True)),
                ('hairColor', models.CharField(max_length=255, null=True)),
                ('hairType', models.CharField(max_length=255, null=True)),
                ('skinTone', models.CharField(max_length=255, null=True)),
                ('eyeColor', models.CharField(max_length=255, null=True)),
                ('clothes', models.CharField(max_length=255, null=True)),
                ('physique', models.CharField(max_length=255, null=True)),
                ('permanent', models.CharField(max_length=255, null=True)),
                ('dispute', models.CharField(max_length=255, null=True)),
                ('reward', models.CharField(max_length=255, null=True)),
                ('nameSus', models.CharField(max_length=255, null=True)),
                ('ageSus', models.CharField(max_length=255, null=True)),
                ('relation', models.CharField(max_length=255, null=True)),
                ('reason', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='db/')),
                ('imageDoc', models.ImageField(null=True, upload_to='imagesDoc/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PoliceCreds',
        ),
    ]
