# Generated by Django 4.0.5 on 2023-03-03 05:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_register_delete_policecreds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
