# Generated by Django 4.0.5 on 2023-03-10 04:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_alter_register_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='govID'),
        ),
    ]
