# Generated by Django 4.0.5 on 2023-03-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_alter_register_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='case_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
