# Generated by Django 4.0.5 on 2023-04-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0005_register_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='case_status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
