# Generated by Django 4.0.5 on 2023-03-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='case_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
