# Generated by Django 4.0.5 on 2023-03-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='govid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
