# Generated by Django 4.0.5 on 2023-04-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0005_notification_govid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rootPoliceStation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
